### ISSUE TITLE
Ajax Completion Event Causing Multiple DIVs

### ISSUE THREAD

**Issue by elbarsal** [mois3x/sweet-alert-rails-confirm#14] opened 2015-03-02 21:47 UTC
Not quite sure of the fix, but I can look into it (more what the repercussions might be) but it looks like the the code called on AJAX completion is re-triggering the SweetAlert initialization routine, which appends an overlay and alert container to the DIV. If you have a page with heavy AJAX interaction, you end up with a lot of extra sweet alert overlays and containers at the bottom of the body.

The code that causes it:

	  $(document).on('ready page:change ajaxComplete', function() {
	    $('[data-sweet-alert-confirm]').on('click', sweetAlertConfirm)
	    //To avoid "Uncaught TypeError: Cannot read property 'querySelector' of null" on turbolinks
	    window.sweetAlertInitialize();
	  });

Which calls this in the core sweet alert:

	  /*
	   * Add modal + overlay to DOM
	   */
	  window.sweetAlertInitialize = function() {
	    var sweetHTML = '<div class="sweet-overlay" ... long line removed ... </div>',
	        sweetWrap = document.createElement('div');

	    sweetWrap.innerHTML = sweetHTML;

	    // Append elements to body
	    while (sweetWrap.firstChild) {
	      document.body.appendChild(sweetWrap.firstChild);
	    }
	  };

I don't know if the correct place to put the fix is probably in the Sweet Alert library (no reason to add the elements if they already exist) or in the sweet alert confirm code (don't reinitialize if it exists). I see there is a comment about turbolinks in this - but I don't know the reasoning there, without digging deeper.

Any thoughts?

**Comment by mois3x** [comment] 2015-03-02 21:56
I think that "dont initialize if exist" could fix the problem here. Are you able to check this and maybe make a PR?

**Comment by elbarsal** [comment] 2015-03-03 02:42
Sure I'll take a look. Anything I should make sure to test? I don't want to break something else, especially with the turbolinks.

**Comment by mois3x** [comment] 2015-03-03 03:52
You can make the pull request and tests will run on travis. You’ll see if fails any. With turbo links i don’t test it yet and i really don’t know i tested manually and it seems to work. You can do it manually and see if its working.

**Comment by mois3x** [comment] 2015-03-03 03:54
I say, i did not covered covered yet turbo links in tests

**Comment by Yaroslav-F** [comment] 2015-06-25 12:29
Any Updates on this? 
Having the same issue with sweet-alert-rails-confirm + ajax jquery datatable integration.

**Comment by mois3x** [comment] 2015-06-26 00:15
Could you provide me the code, i will look at it?

**Comment by Yaroslav-F** [comment] 2015-06-26 05:51
It is quite simple: 
Method with sweet-alert confirm in Datatable class:
```
def actions_link(school)
  links = []
  links << link_to("Settings", settings_path)
  links << link_to("Data", results_path)
  links << link_to("Dashboard", dashboard_path)
  links << link_to("Activity", audits_path)
  links << link_to("X", school_path(school), method: :delete, class: "delete", data: { confirm: "Are you sure you wish to delete this school?", :'confirm-button-text' => 'Delete', :'cancel-button-text' => 'Cancel', :'confirm-button-color' => '#880000', :'sweet-alert-type' => 'warning', text: 'This cannot be undone.', }) if @user.role_is?("Admin")

  links.join
end
```
It is creating action links for every row in the table.

Looking at the html of the table in firefox and chrome - on load, there are three sets of overlay/alert elements at the bottom of the page.

Every time I sort the table by a column heading (AJAX data fetching), another pair of elements is added.
Functionality seems to be fine but this seems very odd?
all just contain:
```
<h2>Title</h2>
<p>Text</p>
```
![image](https://cloud.githubusercontent.com/assets/4863615/8371437/6137e4c2-1be0-11e5-91fe-715dca5d0a89.png)

**Comment by shaun27stars** [comment] 2015-06-29 10:52
$(document).on('ready page:change ajaxComplete', function() {
        $('[data-sweet-alert-confirm]').on('click', sweetAlertConfirm)
        //To avoid "Uncaught TypeError: Cannot read property 'querySelector' of null" on turbolinks
        window.sweetAlertInitialize();
    });

Since, according to the comment, this is calling sweetAlertInitialize in order to avoid an issue with using Turbolinks, it seems that it shouldn't call the initializer on ajaxComplete (which is adding a second element).  So perhaps if we split it in two:

    $(document).on('ready page:change ajaxComplete', function() {
        $('[data-sweet-alert-confirm]').on('click', sweetAlertConfirm)
    });

    $(document).on('ready page:change', function() {
        //To avoid "Uncaught TypeError: Cannot read property 'querySelector' of null" on turbolinks
        window.sweetAlertInitialize();
    });

The first block could simply be bound to the document, too

    $(document).on('click', '[data-sweet-alert-confirm]', sweetAlertConfirm)

I'll see about creating a PR if I have the chance, but this looks like it'd resolve the issue.

**Comment by shaun27stars** [comment] 2015-06-29 14:09
Pull request: https://github.com/mois3x/sweet-alert-rails-confirm/pull/16

It actually should be 

    $(document).on('ready page:load')...

..since <code>page:change</code> is triggered on full page load (in addition to ready), while <code>page:load</code> is only triggered when the page is loaded via turbolinks

**Comment by mois3x** [comment] 2015-06-29 22:00
Thanks so much @shaun27stars, I just pushed the gem. @Yaroslav-F May you try it now?

**Comment by Yaroslav-F** [comment] 2015-06-30 05:53
Works like a charm! Thanks a lot guys! @shaun27stars @mois3x

**Comment by adrianoresende** [comment] 2015-07-01 14:28
For me, It is not done =(
Sweet Alert work perfect but away show this error:
![image](https://cloud.githubusercontent.com/assets/798755/8456694/91d20426-1fe3-11e5-8fd3-12e816c1698f.png)

![image](https://cloud.githubusercontent.com/assets/798755/8456700/9c3b985a-1fe3-11e5-839d-8d468e438a5c.png)

My code:
```
<%= link_to admin_realty_path(realty),
                            :method         => :delete,
                            :'data-toggle'  => 'tooltip',
                            :title          => 'Delete',
                            :data           => { :confirm => 'Are you sure?' } do %>
                  <i class="fa fa-trash-o"></i>
                <% end %>
```

**Comment by mois3x** [comment] 2015-07-02 13:52
Let me get onto this.

**Comment by adrianoresende** [comment] 2015-07-02 14:38
What can I help you?

Check my list JS:
![image](https://cloud.githubusercontent.com/assets/798755/8479535/d203f326-20ae-11e5-85fe-0902e2362e24.png)

**Comment by mois3x** [comment] 2015-07-03 05:17
I cannot reproduce this particular issue that you had @adamrubin but I think that this https://github.com/mois3x/sweet-alert-rails-confirm/tree/tests-turbolinks will fix it. Can you try this branch and give me feedback?.

I've tried to make a good failing test for Turbolinks but it seems that the same bugs that happens in a normal browser don't get in Poltergeist or Capybara-webkit.

**Comment by shaun27stars** [comment] 2015-07-03 08:11
For what it's worth, I can't reproduce this issue either, and I've been using it in a live project since I made the pull request.

I'm curious to know why sweetAlertInitialize wouldn't be defined for you...especially if it still works

**Comment by adrianoresende** [comment] 2015-07-03 13:11
@mois3x Now this is fixed! =D

**Comment by mois3x** [comment] 2015-07-03 19:59
So we should close this issue.

**Closed by mois3x** 2015-07-03 19:59 UTC
